let displayPaletteMethod;  // temp variable for holding function
                           // generated by App by calling setDisplayPalette

export function storeDisplayPaletteMethod(method) {
    displayPaletteMethod = method;
}

export function retrieveDisplayPaletteMethod() {
    return displayPaletteMethod;
}

